name: ðŸž Bug
description: >
  A bug is an issue that differs from documentation or has unexpected behavior.
title: "[BUG] {{ title }}"
labels:
  - "type: bug"
  - "needs: triage"
body:
  - type: checkboxes
    attributes:
      label: Is this issue already tracked somewhere, or is this a new report?
      description: Check if a similar issue has already been reported before submitting a new one.
      options:
        - label: I've reviewed existing issues and couldn't find a duplicate for this problem.
          required: true

  - type: checkboxes
    attributes:
      label: Have you checked the status of Earthdata services?
      description: Earthaccess relies on the Common Metadata Repository (CMR) API and the Earthdata Login (EDL) service to provide its functionality. Please check whether these services are working properly before creating an issue.
      options:
        - label: I've executed `earthaccess.status()` and both CMR and EDL returned `'OK'`.
          required: true

  - type: textarea
    attributes:
      label: Current Behavior
      description: A concise description of what you're experiencing.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: |
        Steps to Reproduce
        1. In this environment...
        2. With this config...
        3. Run '...'
        4. See error...
    validations:
      required: true

  - type: textarea
    attributes:
      label: Environment
      description: |
        Examples:
        - **OS**: Ubuntu 20.04
        - **Python**: 3.11.2
      value: |
        - OS:
        - Python:
      render: markdown
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional Context
      description: |
        Any additional information that might be helpful in resolving this issue, such as:
        - Error messages or stack traces
        - Relevant configuration files or code snippets

        Tip: You can attach files or images by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
