nav:
  - Overview:
      - "What is earthaccess?": "index.md"
      - "Resources": "resources.md"
      - "About Us": "about-us.md"
      - Governance:
          - Decisions: "governance/decisions/"

  - API reference:
      - Search and Access: "api/index.md"
      - Modules:
          - Collections:
              - "Collection Queries": "api/collections/collections-query.md"
              - "Collection Results": "api/collections/collections.md"
              - "Collection Services": "api/collections/collections-services.md"
          - Granules:
              - "Granule Queries": "api/granules/granules-query.md"
              - "Granule Results": "api/granules/granules.md"
          - Store:
              - "Store": "api/store/store.md"
          - Auth:
              - "Auth": "api/auth/auth.md"

  - User guide:
      - "user/index.md"
      - "Quick start": "user/quick-start.md"
      - "Authentication": "user/authenticate.md"
      - "Status": "user/status.md"
      - "Search": "user/search.md"
      - "Access": "user/access.md"
      - "Backwards Compatibility": "user/backwards-compatibility.md"
      - How-tos:
          - "Authenticate with Earthdata Login": "user/howto/authenticate.md"
          - "Search NASA datasets using filters": "user/howto/search-collections.md"
          - "Search for data using filters": "user/howto/search-granules.md"
          - "Determine if a dataset is available in the cloud": "user/howto/storage-location.md"
          - "Access data": "user/howto/access-data.md"
          - "Using authenticated sessions to access data": "user/howto/edl.ipynb"
          - "Remote access and caching with earthaccess": "user/howto/fsspec.ipynb"
          - "Download data from on-prem location": "user/howto/onprem.md"
          - "Direct S3 access - Open/stream files in the cloud": "user/howto/cloud.md"
          - "Search for services": "user/howto/search-services.md"
      - Tutorials:
          - "Accessing remote NASA data with fsspec": "user/tutorials/file-access.ipynb"
          - "Search and access of restricted datasets": "user/tutorials/restricted-datasets.ipynb"
          # - "Reproducing NASA sea level rise infographic": "tutorials/SSL.ipynb" TODO: make this faster
          - "Accessing and visualizing EMIT data with a few lines of code": "user/tutorials/emit-earthaccess.ipynb"
          - "Cloud optimized access to TEMPO air quality data with earthaccess and virtualizarr": "user/tutorials/virtual_dataset_tutorial_with_TEMPO_Level3.ipynb"
      - Reference:
          - Glossary:
              - "NASA Glossary": "user/reference/glossary/nasa-glossary.md"
              - "Cloud Computing Terminology": "user/reference/glossary/cloud-glossary.md"
  - Contributor guide:
      - "contributor/index.md" # << Link target of the parent node
      - "Community calendar": "contributor/calendar.md"
      - "Development Guide": "contributor/development.md"
      - "Pull Request (PR) Guide": "contributor/pr-guide.md"
      - "Releasing Guide": "contributor/releasing.md"
      - "Maintainers Guide": "contributor/maintainers-guide.md"
      - "Triaging Guide": "contributor/triaging.md"
      - "Code of Conduct": "contributor/code-of-conduct.md"
      - "Topics":
          - "Naming conventions": "contributor/naming-convention.md"
          - "Integration tests": "contributor/integration-tests.md"
